import { StudentRecord } from '../types';
import { STANDARD_CERTIFICATES } from '../utils/constants';

const makeCerts = (count: number) =>
  STANDARD_CERTIFICATES.map((name, i) => ({
    id: `cert-${i + 1}`,
    name,
    received: i < count,
    uploadedAt: i < count ? '2026-07-15' : undefined,
  }));

export const INITIAL_STUDENTS: StudentRecord[] = [
  {
    id: 'STU-2026-001',
    personal: {
      applicationNumber: 'ADM001',
      registerNumber: '23CSE001',
      studentName: 'MOHAN KUMAR',
      dateOfBirth: '2005-04-12',
      age: 21,
      aadhaarNumber: '987654321012',
      gender: 'Male',
      district: 'Puducherry',
      nationality: 'Indian',
      caste: 'BC',
    },
    parent: {
      fatherName: 'R. Kumar',
      fatherMobile: '9876543210',
      fatherOccupation: 'Business',
      annualIncome: 350000,
    },
    communication: {
      permanentAddress: {
        addressLine: '12, M.G. Road, Muthialpet',
        pinCode: '605003',
        mobileNumber: '9123456789',
        email: 'mohan.kumar@example.com',
      },
      communicationAddress: {
        addressLine: '12, M.G. Road, Muthialpet',
        pinCode: '605003',
        mobileNumber: '9123456789',
        email: 'mohan.kumar@example.com',
      },
      sameAsPermanent: true,
    },
    academic: {
      admissionCategory: 'CENTAC',
      program: 'First Year B.Tech',
      department: 'Computer Science & Engineering (CSE)',
      batch: '2023 - 2027',
      dateOfAdmission: '2026-07-29',
    },
    hscMarks: {
      stream: 'Academic',
      academicMarks: [
        { subject: 'Maths', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 95, percentage: 95 },
        { subject: 'Physics', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 90, percentage: 90 },
        { subject: 'Chemistry', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 88, percentage: 88 },
      ],
      vocationalMarks: [],
      totalMaxMarks: 300,
      totalMarksObtained: 273,
      overallPercentage: 91,
      engineeringCutOff: 182,
    },
    fee: {
      cutOffMark: 182,
      tuitionFeePerYear: 75000,
      courseDurationYears: 4,
      totalTuitionFee: 300000,
      busRouteSelected: 'Route 1: Puducherry Town - College',
      busFee: 12000,
      hostelRequired: false,
      hostelFee: 0,
      grandTotalFee: 312000,
    },
    certificates: makeCerts(8),
    status: 'Active',
    createdAt: '2026-07-29T10:00:00Z',
    updatedAt: '2026-07-29T10:00:00Z',
  },
  {
    id: 'STU-2026-002',
    personal: {
      applicationNumber: 'ADM002',
      registerNumber: '23ECE014',
      studentName: 'RAHUL SHARMA',
      dateOfBirth: '2005-08-25',
      age: 20,
      aadhaarNumber: '876543210987',
      gender: 'Male',
      district: 'Cuddalore',
      nationality: 'Indian',
      caste: 'MBC',
    },
    parent: {
      fatherName: 'S. Sharma',
      fatherMobile: '9845123760',
      fatherOccupation: 'Government Servant',
      annualIncome: 520000,
    },
    communication: {
      permanentAddress: {
        addressLine: '45, Beach Road, Cuddalore Old Town',
        pinCode: '607003',
        mobileNumber: '9876541230',
        email: 'rahul.sharma@example.com',
      },
      communicationAddress: {
        addressLine: '45, Beach Road, Cuddalore Old Town',
        pinCode: '607003',
        mobileNumber: '9876541230',
        email: 'rahul.sharma@example.com',
      },
      sameAsPermanent: true,
    },
    academic: {
      admissionCategory: 'Management',
      program: 'First Year B.Tech',
      department: 'Electronics & Communication Engineering (ECE)',
      batch: '2023 - 2027',
      dateOfAdmission: '2026-07-29',
    },
    hscMarks: {
      stream: 'Academic',
      academicMarks: [
        { subject: 'Maths', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 88, percentage: 88 },
        { subject: 'Physics', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 84, percentage: 84 },
        { subject: 'Chemistry', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 80, percentage: 80 },
      ],
      vocationalMarks: [],
      totalMaxMarks: 300,
      totalMarksObtained: 252,
      overallPercentage: 84,
      engineeringCutOff: 168,
    },
    fee: {
      cutOffMark: 168,
      tuitionFeePerYear: 125000,
      courseDurationYears: 4,
      totalTuitionFee: 500000,
      busRouteSelected: 'Route 4: Cuddalore - College',
      busFee: 22000,
      hostelRequired: false,
      hostelFee: 0,
      grandTotalFee: 522000,
    },
    certificates: makeCerts(10),
    status: 'Active',
    createdAt: '2026-07-29T11:00:00Z',
    updatedAt: '2026-07-29T11:00:00Z',
  },
  {
    id: 'STU-2026-003',
    personal: {
      applicationNumber: 'ADM003',
      registerNumber: '23EEE007',
      studentName: 'ARJUN KUMAR',
      dateOfBirth: '2005-03-10',
      age: 21,
      aadhaarNumber: '765432109876',
      gender: 'Male',
      district: 'Puducherry',
      nationality: 'Indian',
      caste: 'OC',
    },
    parent: {
      fatherName: 'P. Kumar',
      fatherMobile: '9789012345',
      fatherOccupation: 'Private',
      annualIncome: 400000,
    },
    communication: {
      permanentAddress: {
        addressLine: '7, Anna Street, Puducherry',
        pinCode: '605001',
        mobileNumber: '9443210987',
        email: 'arjun.kumar@example.com',
      },
      communicationAddress: {
        addressLine: '7, Anna Street, Puducherry',
        pinCode: '605001',
        mobileNumber: '9443210987',
        email: 'arjun.kumar@example.com',
      },
      sameAsPermanent: true,
    },
    academic: {
      admissionCategory: 'CENTAC',
      program: 'First Year B.Tech',
      department: 'Electrical & Electronics Engineering (EEE)',
      batch: '2023 - 2027',
      dateOfAdmission: '2026-07-28',
    },
    hscMarks: {
      stream: 'Academic',
      academicMarks: [
        { subject: 'Maths', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 92, percentage: 92 },
        { subject: 'Physics', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 87, percentage: 87 },
        { subject: 'Chemistry', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 85, percentage: 85 },
      ],
      vocationalMarks: [],
      totalMaxMarks: 300,
      totalMarksObtained: 264,
      overallPercentage: 88,
      engineeringCutOff: 176,
    },
    fee: {
      cutOffMark: 176,
      tuitionFeePerYear: 75000,
      courseDurationYears: 4,
      totalTuitionFee: 300000,
      busRouteSelected: 'Route 1: Puducherry Town - College',
      busFee: 12000,
      hostelRequired: false,
      hostelFee: 0,
      grandTotalFee: 312000,
    },
    certificates: makeCerts(7),
    status: 'Active',
    createdAt: '2026-07-28T09:00:00Z',
    updatedAt: '2026-07-28T09:00:00Z',
  },
  {
    id: 'STU-2026-004',
    personal: {
      applicationNumber: 'ADM004',
      registerNumber: '23MECH012',
      studentName: 'PRIYA DEVI',
      dateOfBirth: '2005-06-15',
      age: 21,
      aadhaarNumber: '654321098765',
      gender: 'Female',
      district: 'Villupuram',
      nationality: 'Indian',
      caste: 'BC',
    },
    parent: {
      fatherName: 'M. Rajan',
      fatherMobile: '9751234560',
      fatherOccupation: 'Agriculture',
      annualIncome: 250000,
    },
    communication: {
      permanentAddress: {
        addressLine: '34, Nehru Nagar, Villupuram',
        pinCode: '605602',
        mobileNumber: '9543210876',
        email: 'priya.devi@example.com',
      },
      communicationAddress: {
        addressLine: '34, Nehru Nagar, Villupuram',
        pinCode: '605602',
        mobileNumber: '9543210876',
        email: 'priya.devi@example.com',
      },
      sameAsPermanent: true,
    },
    academic: {
      admissionCategory: 'Management',
      program: 'First Year B.Tech',
      department: 'Mechanical Engineering (MECH)',
      batch: '2023 - 2027',
      dateOfAdmission: '2026-07-28',
    },
    hscMarks: {
      stream: 'Academic',
      academicMarks: [
        { subject: 'Maths', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 78, percentage: 78 },
        { subject: 'Physics', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 75, percentage: 75 },
        { subject: 'Chemistry', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 72, percentage: 72 },
      ],
      vocationalMarks: [],
      totalMaxMarks: 300,
      totalMarksObtained: 225,
      overallPercentage: 75,
      engineeringCutOff: 150,
    },
    fee: {
      cutOffMark: 150,
      tuitionFeePerYear: 95000,
      courseDurationYears: 4,
      totalTuitionFee: 380000,
      busRouteSelected: 'Route 5: Tindivanam - College',
      busFee: 25000,
      hostelRequired: true,
      hostelFee: 65000,
      grandTotalFee: 470000,
    },
    certificates: makeCerts(9),
    status: 'Active',
    createdAt: '2026-07-28T10:30:00Z',
    updatedAt: '2026-07-28T10:30:00Z',
  },
  {
    id: 'STU-2026-005',
    personal: {
      applicationNumber: 'ADM005',
      registerNumber: '23IT021',
      studentName: 'KEERTHANA R',
      dateOfBirth: '2005-11-20',
      age: 20,
      aadhaarNumber: '543210987654',
      gender: 'Female',
      district: 'Puducherry',
      nationality: 'Indian',
      caste: 'MBC',
    },
    parent: {
      fatherName: 'K. Rajan',
      fatherMobile: '9632145870',
      fatherOccupation: 'Business',
      annualIncome: 480000,
    },
    communication: {
      permanentAddress: {
        addressLine: '56, Gandhi Nagar, Puducherry',
        pinCode: '605009',
        mobileNumber: '9876549870',
        email: 'keerthana.r@example.com',
      },
      communicationAddress: {
        addressLine: '56, Gandhi Nagar, Puducherry',
        pinCode: '605009',
        mobileNumber: '9876549870',
        email: 'keerthana.r@example.com',
      },
      sameAsPermanent: true,
    },
    academic: {
      admissionCategory: 'CENTAC',
      program: 'First Year B.Tech',
      department: 'Information Technology (IT)',
      batch: '2023 - 2027',
      dateOfAdmission: '2026-07-27',
    },
    hscMarks: {
      stream: 'Academic',
      academicMarks: [
        { subject: 'Maths', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 93, percentage: 93 },
        { subject: 'Physics', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 89, percentage: 89 },
        { subject: 'Chemistry', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 87, percentage: 87 },
      ],
      vocationalMarks: [],
      totalMaxMarks: 300,
      totalMarksObtained: 269,
      overallPercentage: 89.67,
      engineeringCutOff: 179,
    },
    fee: {
      cutOffMark: 179,
      tuitionFeePerYear: 75000,
      courseDurationYears: 4,
      totalTuitionFee: 300000,
      busRouteSelected: 'Route 1: Puducherry Town - College',
      busFee: 12000,
      hostelRequired: false,
      hostelFee: 0,
      grandTotalFee: 312000,
    },
    certificates: makeCerts(8),
    status: 'Active',
    createdAt: '2026-07-27T09:30:00Z',
    updatedAt: '2026-07-27T09:30:00Z',
  },
  {
    id: 'STU-2026-006',
    personal: {
      applicationNumber: 'ADM006',
      registerNumber: '23CIV009',
      studentName: 'SURESH KUMAR',
      dateOfBirth: '2005-02-28',
      age: 21,
      aadhaarNumber: '432109876543',
      gender: 'Male',
      district: 'Cuddalore',
      nationality: 'Indian',
      caste: 'SC',
    },
    parent: {
      fatherName: 'S. Murugan',
      fatherMobile: '9514723680',
      fatherOccupation: 'Labour',
      annualIncome: 180000,
    },
    communication: {
      permanentAddress: {
        addressLine: '22, Raja Street, Cuddalore',
        pinCode: '607001',
        mobileNumber: '9381234560',
        email: 'suresh.kumar@example.com',
      },
      communicationAddress: {
        addressLine: '22, Raja Street, Cuddalore',
        pinCode: '607001',
        mobileNumber: '9381234560',
        email: 'suresh.kumar@example.com',
      },
      sameAsPermanent: true,
    },
    academic: {
      admissionCategory: 'Management',
      program: 'First Year B.Tech',
      department: 'Civil Engineering (CIVIL)',
      batch: '2023 - 2027',
      dateOfAdmission: '2026-07-27',
    },
    hscMarks: {
      stream: 'Academic',
      academicMarks: [
        { subject: 'Maths', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 70, percentage: 70 },
        { subject: 'Physics', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 68, percentage: 68 },
        { subject: 'Chemistry', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 65, percentage: 65 },
      ],
      vocationalMarks: [],
      totalMaxMarks: 300,
      totalMarksObtained: 203,
      overallPercentage: 67.67,
      engineeringCutOff: 135,
    },
    fee: {
      cutOffMark: 135,
      tuitionFeePerYear: 75000,
      courseDurationYears: 4,
      totalTuitionFee: 300000,
      busRouteSelected: 'Route 4: Cuddalore - College',
      busFee: 22000,
      hostelRequired: false,
      hostelFee: 0,
      grandTotalFee: 322000,
    },
    certificates: makeCerts(6),
    status: 'Active',
    createdAt: '2026-07-27T11:00:00Z',
    updatedAt: '2026-07-27T11:00:00Z',
  },
  {
    id: 'STU-2026-007',
    personal: {
      applicationNumber: 'ADM007',
      registerNumber: '23CSE018',
      studentName: 'ANITHA M',
      dateOfBirth: '2005-09-05',
      age: 20,
      aadhaarNumber: '321098765432',
      gender: 'Female',
      district: 'Puducherry',
      nationality: 'Indian',
      caste: 'BC',
    },
    parent: {
      fatherName: 'M. Selvam',
      fatherMobile: '9487654321',
      fatherOccupation: 'Private',
      annualIncome: 320000,
    },
    communication: {
      permanentAddress: {
        addressLine: '88, Thiruvalluvar Nagar, Puducherry',
        pinCode: '605005',
        mobileNumber: '9487654321',
        email: 'anitha.m@example.com',
      },
      communicationAddress: {
        addressLine: '88, Thiruvalluvar Nagar, Puducherry',
        pinCode: '605005',
        mobileNumber: '9487654321',
        email: 'anitha.m@example.com',
      },
      sameAsPermanent: true,
    },
    academic: {
      admissionCategory: 'CENTAC',
      program: 'First Year B.Tech',
      department: 'Computer Science & Engineering (CSE)',
      batch: '2023 - 2027',
      dateOfAdmission: '2026-07-26',
    },
    hscMarks: {
      stream: 'Academic',
      academicMarks: [
        { subject: 'Maths', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 90, percentage: 90 },
        { subject: 'Physics', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 86, percentage: 86 },
        { subject: 'Chemistry', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 84, percentage: 84 },
      ],
      vocationalMarks: [],
      totalMaxMarks: 300,
      totalMarksObtained: 260,
      overallPercentage: 86.67,
      engineeringCutOff: 174,
    },
    fee: {
      cutOffMark: 174,
      tuitionFeePerYear: 75000,
      courseDurationYears: 4,
      totalTuitionFee: 300000,
      busRouteSelected: 'Route 1: Puducherry Town - College',
      busFee: 12000,
      hostelRequired: false,
      hostelFee: 0,
      grandTotalFee: 312000,
    },
    certificates: makeCerts(9),
    status: 'Active',
    createdAt: '2026-07-26T09:00:00Z',
    updatedAt: '2026-07-26T09:00:00Z',
  },
  {
    id: 'STU-2026-008',
    personal: {
      applicationNumber: 'ADM008',
      registerNumber: '23ECE022',
      studentName: 'VIGNESH S',
      dateOfBirth: '2005-07-12',
      age: 21,
      aadhaarNumber: '210987654321',
      gender: 'Male',
      district: 'Karaikal',
      nationality: 'Indian',
      caste: 'MBC',
    },
    parent: {
      fatherName: 'S. Senthil',
      fatherMobile: '9361234780',
      fatherOccupation: 'Fisherman',
      annualIncome: 200000,
    },
    communication: {
      permanentAddress: {
        addressLine: '15, Seashore Road, Karaikal',
        pinCode: '609602',
        mobileNumber: '9361234780',
        email: 'vignesh.s@example.com',
      },
      communicationAddress: {
        addressLine: '15, Seashore Road, Karaikal',
        pinCode: '609602',
        mobileNumber: '9361234780',
        email: 'vignesh.s@example.com',
      },
      sameAsPermanent: true,
    },
    academic: {
      admissionCategory: 'CENTAC',
      program: 'First Year B.Tech',
      department: 'Electronics & Communication Engineering (ECE)',
      batch: '2023 - 2027',
      dateOfAdmission: '2026-07-26',
    },
    hscMarks: {
      stream: 'Academic',
      academicMarks: [
        { subject: 'Maths', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 85, percentage: 85 },
        { subject: 'Physics', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 82, percentage: 82 },
        { subject: 'Chemistry', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 80, percentage: 80 },
      ],
      vocationalMarks: [],
      totalMaxMarks: 300,
      totalMarksObtained: 247,
      overallPercentage: 82.33,
      engineeringCutOff: 165,
    },
    fee: {
      cutOffMark: 165,
      tuitionFeePerYear: 75000,
      courseDurationYears: 4,
      totalTuitionFee: 300000,
      busRouteSelected: 'Route 1: Puducherry Town - College',
      busFee: 12000,
      hostelRequired: true,
      hostelFee: 65000,
      grandTotalFee: 377000,
    },
    certificates: makeCerts(8),
    status: 'Active',
    createdAt: '2026-07-26T10:30:00Z',
    updatedAt: '2026-07-26T10:30:00Z',
  },
  {
    id: 'STU-2026-009',
    personal: {
      applicationNumber: 'ADM009',
      registerNumber: '23IT015',
      studentName: 'NANDHINI P',
      dateOfBirth: '2005-12-08',
      age: 20,
      aadhaarNumber: '109876543210',
      gender: 'Female',
      district: 'Puducherry',
      nationality: 'Indian',
      caste: 'OC',
    },
    parent: {
      fatherName: 'P. Vijay',
      fatherMobile: '9245678901',
      fatherOccupation: 'Businessman',
      annualIncome: 600000,
    },
    communication: {
      permanentAddress: {
        addressLine: '42, Nehru Street, Pondicherry',
        pinCode: '605001',
        mobileNumber: '9245678901',
        email: 'nandhini.p@example.com',
      },
      communicationAddress: {
        addressLine: '42, Nehru Street, Pondicherry',
        pinCode: '605001',
        mobileNumber: '9245678901',
        email: 'nandhini.p@example.com',
      },
      sameAsPermanent: true,
    },
    academic: {
      admissionCategory: 'Management',
      program: 'First Year B.Tech',
      department: 'Information Technology (IT)',
      batch: '2023 - 2027',
      dateOfAdmission: '2026-07-25',
    },
    hscMarks: {
      stream: 'Academic',
      academicMarks: [
        { subject: 'Maths', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 96, percentage: 96 },
        { subject: 'Physics', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 92, percentage: 92 },
        { subject: 'Chemistry', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 90, percentage: 90 },
      ],
      vocationalMarks: [],
      totalMaxMarks: 300,
      totalMarksObtained: 278,
      overallPercentage: 92.67,
      engineeringCutOff: 186,
    },
    fee: {
      cutOffMark: 186,
      tuitionFeePerYear: 125000,
      courseDurationYears: 4,
      totalTuitionFee: 500000,
      busRouteSelected: 'Route 1: Puducherry Town - College',
      busFee: 12000,
      hostelRequired: false,
      hostelFee: 0,
      grandTotalFee: 512000,
    },
    certificates: makeCerts(10),
    status: 'Active',
    createdAt: '2026-07-25T09:00:00Z',
    updatedAt: '2026-07-25T09:00:00Z',
  },
  {
    id: 'STU-2026-010',
    personal: {
      applicationNumber: 'ADM010',
      registerNumber: '23MECH019',
      studentName: 'KARTHIK R',
      dateOfBirth: '2005-05-18',
      age: 21,
      aadhaarNumber: '098765432109',
      gender: 'Male',
      district: 'Villupuram',
      nationality: 'Indian',
      caste: 'BC',
    },
    parent: {
      fatherName: 'R. Selvam',
      fatherMobile: '9123456780',
      fatherOccupation: 'Driver',
      annualIncome: 220000,
    },
    communication: {
      permanentAddress: {
        addressLine: '67, Market Street, Villupuram',
        pinCode: '605602',
        mobileNumber: '9123456780',
        email: 'karthik.r@example.com',
      },
      communicationAddress: {
        addressLine: '67, Market Street, Villupuram',
        pinCode: '605602',
        mobileNumber: '9123456780',
        email: 'karthik.r@example.com',
      },
      sameAsPermanent: true,
    },
    academic: {
      admissionCategory: 'CENTAC',
      program: 'First Year B.Tech',
      department: 'Mechanical Engineering (MECH)',
      batch: '2023 - 2027',
      dateOfAdmission: '2026-07-25',
    },
    hscMarks: {
      stream: 'Academic',
      academicMarks: [
        { subject: 'Maths', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 82, percentage: 82 },
        { subject: 'Physics', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 78, percentage: 78 },
        { subject: 'Chemistry', monthYear: 'Mar 2023', maxMarks: 100, marksObtained: 76, percentage: 76 },
      ],
      vocationalMarks: [],
      totalMaxMarks: 300,
      totalMarksObtained: 236,
      overallPercentage: 78.67,
      engineeringCutOff: 158,
    },
    fee: {
      cutOffMark: 158,
      tuitionFeePerYear: 75000,
      courseDurationYears: 4,
      totalTuitionFee: 300000,
      busRouteSelected: 'Route 5: Tindivanam - College',
      busFee: 25000,
      hostelRequired: false,
      hostelFee: 0,
      grandTotalFee: 325000,
    },
    certificates: makeCerts(7),
    status: 'Active',
    createdAt: '2026-07-25T11:00:00Z',
    updatedAt: '2026-07-25T11:00:00Z',
  },
];

export const INITIAL_ARCHIVED_STUDENTS: StudentRecord[] = [];
